# -- Site Settings --
title: Jekyll Bootstrapped
baseurl: "/Jekyll-Bootstrapped"
url: "https://skrillx13.github.io"

# -- Build Configuration --
plugins:
  - jekyll-feed

# -- Excluded Items --
exclude:
  - README.md # Project README, which Shouldn't be included in the site.
  - LICENSE # Project LICENSE, with the same reasoning as the README
  - .gitignore # A list of ignored files that shouldn't be pushed to the GitHub Repo
  - Gemfile # A list of Ruby Packages
  - Gemfile.lock # More Ruby Packaging
  - _site # Jekyll Rendered Site
  - .jekyll-cache # More Jekyll Stuff

# -- Theming --
github: Skrillx13/Jekyll-Bootstrapped