# -- Site Settings --
title: Jekyll Bootstrapped
baseurl: "/Jekyll-Bootstrapped"
url: "https://skrillx13.github.io"

# -- Build Configuration --
plugins:
  - jekyll-feed

# -- Excluded Items --
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock